# Site settings
baseurl = "https://aounleonardo.github.io/"
languageCode = "en-us"
title = "Travelling Codesman"
theme = "hugo-freelancer-theme"
publishDir = "aounleonardo.github.io"


[params]

    # You can use Markdown syntax for urls [text](//url.to/source) for
    # most longer texts.

    # To provide some metadata for search engines feel free to add a few
    # information about you and your website.
    name = "Leonardo Aoun"
    description = "Travelling Codesman"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email youself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    email = "aounleonardo96@gmail.com"

    # Custom assets
	custom_css = []
	custom_js  = []

    [params.navigation]
        brand = "Leonardo Aoun"


    [params.header]
        # Copy your own image into './static/img/'' if you wish
        image = "profile_sm.png"
        name = "Leonardo Aoun"
        subtitle = "Travelling Codesman"


    [params.education]
        # All projects defined in their own files. You can find example projects
        # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
        # at the root of this Hugo site.
        # For more informtion take a look at the README.
        title = "Education"

        [params.education.modal]
            date = "Date"
            location = "Location"
            category = "Degree"
            buttontext = "Close"


    [params.experience]
        # All projects defined in their own files. You can find example projects
        # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
        # at the root of this Hugo site.
        # For more informtion take a look at the README.
        title = "Experience"

        [params.experience.modal]
            date = "Date"
            location = "Location"
            category = "Position"
            buttontext = "Close"


    [params.portfolio]
        # All projects defined in their own files. You can find example projects
        # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
        # at the root of this Hugo site.
        # For more informtion take a look at the README.
        title = "Projects"

        [params.portfolio.modal]
            date = "Date"
            category = "Category"
            buttontext = "Close"


    [params.about]
        title = "About"
        # The about text is splitted into a left and right column
        left = "I am a Lebanese graduate from EPFL, Switzerland who majored in CSE. Experienced in machine learning, full stack development, and travelling."
        right = "I Lived in 8 regions across 3 continents in the last 3 years which taught me to be a sociable and open-minded person. Inspired by science and always eager to discover and invent."

        [params.about.button]
            text = "Download Resume"
            link = "/files/Resume.pdf"
            icon = "download"


    [params.footer]
        copyright = "Borrowed under the Apache License 2.0 from [Start Bootstrap](//startbootstrap.com). Powered by [Hugo](//gohugo.io)."

        [params.footer.social]
            title = "Around the web"
            # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
            # for more icons. The icons are represented by their corresponding
            # CSS class.
            [[params.footer.social.networks]]
                icon = "fa-github"
                link = "//github.com/spf13/hugo"

            [[params.footer.social.networks]]
                icon = "fa-facebook"
                link=  "//stackoverflow.com/questions/tagged/hugo"

            [[params.footer.social.networks]]
                icon = "fa-twitter"
                link=  "//stackoverflow.com/questions/tagged/hugo"

            [[params.footer.social.networks]]
                icon = "fa-linkedin"
                link=  "//stackoverflow.com/questions/tagged/hugo"

            [[params.footer.social.networks]]
                icon = "fa-envelope"
                link=  "mailto:aounleonardo96@gmail.com"
